### PR TITLE
Add attributes to toTransaction

### PR DESCRIPTION
**Pull request by vilenarios**
This PR adds `attributes: Partial<CreateTransactionInterface>` to all `toTransaction` methods.  This allows Bundle transactions to have (for example) a target and quantity when `bundle.toTransaction()` is called.

Arweave-js was also updated to the latest version (1.10.18) which fixed type incompatibility issues.

### CODE REVIEW

**Comment by hlolli** [comment]
see if the tests succeed after rebasing the branch to master

**Comment by joshbenaron** [comment]
This is an issue with Arweave versions. I'd probably say this is an issue with arweave-js as minor version changes shouldn't cause this issue

**Comment by hlolli** [comment]
this PR is based on #1976030eba3953dcd7582e65b50217f893f6248d the error could disappear if it's merged with master

**Comment by joshbenaron** [comment]
Can you upstream merge from master? There shouldn't be any build errors

**Comment by vilenarios** [comment]
Merged from master!  Let me know how it looks.

**Comment by vilenarios** [comment]
Arweave streams updated to v1.1.0 which should fix the arweave-js dependency conflicts.

**Comment by joshbenaron** [comment]
LGTM

**Pull request merged**
